service: nukos-choise

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - ${self:provider.region}
            - ':'
            - Ref: AWS::AccountId
            - ':table/'
            - Ref: OrderTable

functions:
  nukos-choice:
    name: nukos-choice
    handler: handler.main
    # events:
    #   - schedule: cron(0 0 ? * MON-FRI *)

resources:
  Resources:
    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrderTable
        AttributeDefinitions:
          - AttributeName: order
            AttributeType: N
        KeySchema:
          - AttributeName: order
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
